<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalAi.Broker.Core\LocalAi.Broker.Core.csproj" />
    <ProjectReference Include="..\LocalAi.Contracts\LocalAi.Contracts.csproj" />
  </ItemGroup>

</Project>
