using CodeSearch.Core.Chunking;

namespace CodeSearch.Tests;

public class RoslynChunkerTests
{
    private readonly RoslynChunker _chunker = new();

    private const string Sample = """
        namespace Intelwash.Orders;

        /// <summary>Closes orders once payment lands.</summary>
        public sealed class OrderCloser : IOrderCloser
        {
            private readonly IClock _clock;

            public int ClosedCount { get; private set; }

            public OrderCloser(IClock clock) => _clock = clock;

            /// <summary>Closes the order.</summary>
            public async Task<bool> CloseAsync(Guid orderId, CancellationToken ct)
            {
                await Task.Delay(1, ct);
                ClosedCount++;
                return true;
            }
        }
        """;

    [Fact]
    public void EmitsOneChunkPerTypeAndPerExecutableMember()
    {
        var chunks = _chunker.Split("Orders/OrderCloser.cs", Sample).ToList();

        Assert.Single(chunks, c => c.Kind == ChunkKind.Type && c.Symbol == "OrderCloser");
        Assert.Contains(chunks, c => c.Kind == ChunkKind.Method && c.Symbol == "OrderCloser.CloseAsync");
        Assert.Contains(chunks, c => c.Kind == ChunkKind.Method && c.Symbol == "OrderCloser.OrderCloser");
    }

    [Fact]
    public void AutoPropertiesAndFieldsDoNotGetTheirOwnChunks()
    {
        var chunks = _chunker.Split("Orders/OrderCloser.cs", Sample).ToList();

        // They ride along inside the type chunk instead - a 20-property DTO must not become
        // 21 vectors.
        Assert.DoesNotContain(chunks, c => c.Symbol == "OrderCloser.ClosedCount");
        Assert.DoesNotContain(chunks, c => c.Symbol.Contains("_clock"));

        var type = chunks.Single(c => c.Kind == ChunkKind.Type);
        Assert.Contains("ClosedCount", type.EmbedText);
        Assert.Contains("_clock", type.EmbedText);
    }

    [Fact]
    public void TypeChunkListsMethodSignaturesSoItCanAnswerWhatTheClassDoes()
    {
        var type = _chunker.Split("Orders/OrderCloser.cs", Sample).Single(c => c.Kind == ChunkKind.Type);

        Assert.Contains("CloseAsync", type.EmbedText);
        Assert.Contains("IOrderCloser", type.EmbedText); // base list survives in the declaration
    }

    [Fact]
    public void CarriesNamespaceDocCommentAndExactLineNumbers()
    {
        var chunks = _chunker.Split("Orders/OrderCloser.cs", Sample).ToList();
        var method = chunks.Single(c => c.Symbol == "OrderCloser.CloseAsync");

        Assert.Equal("Intelwash.Orders", method.Namespace);
        Assert.Contains("Closes the order.", method.EmbedText);
        Assert.Contains("Type: OrderCloser", method.EmbedText);

        var lines = SourceLines.Split(Sample);
        Assert.Contains("CloseAsync", lines[method.StartLine - 1]);
        Assert.True(method.EndLine > method.StartLine);
    }

    [Fact]
    public void PropertyWithRealLogicGetsItsOwnChunk()
    {
        const string source = """
            public class Cart
            {
                public decimal Total
                {
                    get
                    {
                        var sum = 0m;
                        foreach (var line in Lines) { sum += line.Price; }
                        return sum;
                    }
                }
            }
            """;

        var chunks = _chunker.Split("Cart.cs", source).ToList();
        Assert.Contains(chunks, c => c.Kind == ChunkKind.Method && c.Symbol == "Cart.Total");
    }

    [Fact]
    public void NestedTypesReadAsOuterDotInner()
    {
        const string source = """
            public class Outer
            {
                public class Inner
                {
                    public void Go() { }
                }
            }
            """;

        var chunks = _chunker.Split("Outer.cs", source).ToList();
        Assert.Contains(chunks, c => c.Kind == ChunkKind.Type && c.Symbol == "Outer.Inner");
        Assert.Contains(chunks, c => c.Symbol == "Outer.Inner.Go");
    }

    [Fact]
    public void GeneratedFilesAreSkippedEntirely()
    {
        const string source = """
            // <auto-generated />
            public class Generated { public void Go() { } }
            """;

        Assert.Empty(_chunker.Split("Generated.cs", source));
    }

    [Fact]
    public void OversizedMemberSplitsIntoOverlappingPartsWithinTheCharBudget()
    {
        var body = string.Join('\n', Enumerable.Range(0, 900)
            .Select(i => $"        var value{i} = ComputeSomethingWithAFairlyLongName({i});"));

        var source = $$"""
            public class Big
            {
                public void Huge()
                {
            {{body}}
                }
            }
            """;

        var parts = _chunker.Split("Big.cs", source)
            .Where(c => c.Symbol.StartsWith("Big.Huge"))
            .ToList();

        Assert.True(parts.Count > 1, "a 900-line method must not become a single chunk");
        Assert.All(parts, p => Assert.True(p.EmbedText.Length <= ChunkLimits.MaxChars));
        Assert.All(parts, p => Assert.Contains("Type: Big", p.EmbedText));

        // Parts must overlap, so a construct on a seam is never split away from its context.
        Assert.True(parts[1].StartLine < parts[0].EndLine);
    }

    [Fact]
    public void FileWithoutTypesStillProducesAChunk()
    {
        var chunks = _chunker.Split("GlobalUsings.cs", "global using System;\nglobal using Xunit;").ToList();

        Assert.Single(chunks);
        Assert.Equal(ChunkKind.File, chunks[0].Kind);
    }
}
