using System.Globalization;
using System.IO.Compression;
using System.Numerics;
using System.Security.Cryptography;
using System.Text.Json;
using LocalAi.Contracts;
using LocalAi.Installer.Core.Abstractions;
using LocalAi.Installer.Core.Models;
using LocalAi.Installer.Core.Releases;

namespace LocalAi.ReleaseSigner;

/// <summary>
/// Produces the signed release manifest that the installer verifies.
///
/// The manifest bytes are generated by <see cref="ReleaseManifestVerifier.CreateCanonicalUnsignedPayload"/>
/// rather than by a local serializer: the verifier compares the published document to that
/// canonical form byte for byte, so producing it any other way invites a silent drift that
/// only shows up as a failed installation.
/// </summary>
internal static class Program
{
    private static readonly BigInteger P256Order = BigInteger.Parse(
        "00FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551",
        NumberStyles.HexNumber);

    private static int Main(string[] args)
    {
        try
        {
            return args.FirstOrDefault() switch
            {
                "pack" => Pack(Args.Parse(args.Skip(1))),
                "models" => Models(Args.Parse(args.Skip(1))).GetAwaiter().GetResult(),
                "sign" => Sign(Args.Parse(args.Skip(1))),
                "verify" => Verify(Args.Parse(args.Skip(1))),
                "verify-package" => VerifyPackage(Args.Parse(args.Skip(1))).GetAwaiter().GetResult(),
                "release" => Release(Args.Parse(args.Skip(1))).GetAwaiter().GetResult(),
                _ => Usage(),
            };
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception.Message);
            return 1;
        }
    }

    private static int Usage()
    {
        Console.Error.WriteLine(
            """
            Usage:
              localai-release-signer pack --input <directory> --release-version <1.2.3>
                                          --version-directory <name>
                                          [--model-catalog-version <name>] --out <zip>

              localai-release-signer models --out <file>

              localai-release-signer sign --package <file> --package-uri <https url>
                                          --release-version <1.2.3> --version-directory <name>
                                          [--model-catalog-version <name>]
                                          (--models <file> | --no-models)
                                          [--require-authenticode] [--private-key <file>]
                                          --out <directory>

              localai-release-signer verify --manifest <file> --signature <file>
                                            [--public-key <file>]

              localai-release-signer release --version <1.2.3> [--publish] [--root <directory>]

            Without --publish this scaffolds the release notes, checks them, and opens the pull
            request that carries them. With it, and only from the merged commit on main, it
            builds, signs, verifies that the manifest describes this release, and then tags and
            publishes. The two halves are separate invocations because the second one is not
            reversible.

            `models` reads the download size of every catalogue model from the public model
            registry and writes the list `sign` embeds in the manifest. The installer installs
            only models the signed manifest names, so `sign` demands that list explicitly:
            pass --models, or --no-models to publish a release that installs none on purpose.

            The private key defaults to
            %LOCALAPPDATA%\LocalAi\release-signing\release-signing-private.pkcs8.der.
            The public key defaults to the key embedded in the installer build.
            """);
        return 2;
    }

    /// <summary>
    /// Builds the release package. The verifier compares the archive entry names against
    /// <see cref="LocalAiPackageLayout.PackageArtifactFiles"/> with SetEquals, so the archive
    /// must hold exactly those files plus the metadata document — flat, with no directory
    /// entries and nothing extra. That in turn means the executables have to be published
    /// self-contained: there is no room in the format for sibling dependency assemblies.
    /// </summary>
    private static int Pack(Args args)
    {
        var input = args.Require("input");
        var releaseVersion = args.Require("release-version");
        var versionDirectory = args.Require("version-directory");
        var modelCatalogVersion = args.Optional("model-catalog-version") ?? "1";

        var missing = LocalAiPackageLayout.PackageArtifactFiles
            .Where(file => !File.Exists(Path.Combine(input, file)))
            .ToArray();
        if (missing.Length > 0)
        {
            throw new InvalidOperationException(
                $"Missing package artifacts in {input}: {string.Join(", ", missing)}");
        }

        var metadata = BuildPackageMetadata(releaseVersion, versionDirectory, modelCatalogVersion);
        var output = args.Require("out");
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
        if (File.Exists(output))
        {
            File.Delete(output);
        }

        using (var archive = new ZipArchive(File.Create(output), ZipArchiveMode.Create))
        {
            foreach (var file in LocalAiPackageLayout.PackageArtifactFiles)
            {
                var entry = archive.CreateEntry(file, CompressionLevel.Optimal);
                using var target = entry.Open();
                using var source = File.OpenRead(Path.Combine(input, file));
                source.CopyTo(target);
            }

            var metadataEntry = archive.CreateEntry(
                ReleasePackageVerifier.PackageMetadataFileName,
                CompressionLevel.Optimal);
            using var metadataStream = metadataEntry.Open();
            metadataStream.Write(metadata);
        }

        var package = new FileInfo(output);
        Console.WriteLine($"package : {package.FullName}");
        Console.WriteLine($"entries : {LocalAiPackageLayout.PackageArtifactFiles.Count + 1}");
        Console.WriteLine($"size    : {package.Length:N0} bytes");
        Console.WriteLine($"sha256  : {Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(output)))}");
        return 0;
    }

    /// <summary>
    /// The verifier rebuilds this document itself and compares byte for byte, so the
    /// property order and the absence of whitespace and BOM are part of the contract.
    /// </summary>
    private static byte[] BuildPackageMetadata(
        string releaseVersion,
        string versionDirectory,
        string modelCatalogVersion) =>
        System.Text.Encoding.UTF8.GetBytes(
            $"{{\"SchemaVersion\":1," +
            $"\"ReleaseVersion\":{JsonSerializer.Serialize(releaseVersion)}," +
            $"\"VersionDirectory\":{JsonSerializer.Serialize(versionDirectory)}," +
            $"\"ModelCatalogVersion\":{JsonSerializer.Serialize(modelCatalogVersion)}," +
            $"\"ProtocolVersion\":{BrokerCompatibilityContract.ProtocolVersion.ToString(CultureInfo.InvariantCulture)}," +
            $"\"BuildCompatibilityId\":{JsonSerializer.Serialize(BrokerCompatibilityContract.BuildCompatibilityId)}}}");

    /// <summary>
    /// Writes the model list for a release, sized from the public registry at this moment.
    /// </summary>
    private static async Task<int> Models(Args args)
    {
        var output = Path.GetFullPath(args.Require("out"));
        using var registry = new OllamaRegistryClient(TimeSpan.FromSeconds(30));
        var entries = await ReleaseModelList.BuildAsync(registry);
        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        await File.WriteAllTextAsync(output, ReleaseModelList.Render(entries));

        Console.WriteLine($"models  : {output}");
        Console.WriteLine($"entries : {entries.Count}");
        foreach (var group in entries.GroupBy(entry => entry.Name, StringComparer.Ordinal))
        {
            Console.WriteLine(
                $"  {group.Key}: {group.First().DownloadSize / (1024d * 1024 * 1024):N1} GB, " +
                $"{group.Count()} context sizes");
        }

        return 0;
    }

    private static int Sign(Args args)
    {
        var packagePath = args.Require("package");
        var package = new FileInfo(packagePath);
        if (!package.Exists)
        {
            throw new InvalidOperationException($"Package not found: {packagePath}");
        }

        var manifest = new ReleaseManifest(
            schemaVersion: 1,
            releaseVersion: args.Require("release-version"),
            versionDirectory: args.Require("version-directory"),
            modelCatalogVersion: args.Optional("model-catalog-version") ?? "1",
            protocolVersion: BrokerCompatibilityContract.ProtocolVersion,
            buildCompatibilityId: BrokerCompatibilityContract.BuildCompatibilityId,
            packageUri: new Uri(args.Require("package-uri"), UriKind.Absolute),
            packageSize: package.Length,
            // The verifier accepts upper-case hex only.
            packageSha256: Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(packagePath))),
            requiresAuthenticode: args.Flag("require-authenticode"),
            models: ReadModels(args.Optional("models"), args.Flag("no-models")));

        // Throws if any field violates the manifest contract, so a bad release fails here
        // rather than on the user's machine.
        var canonical = ReleaseManifestVerifier.CreateCanonicalUnsignedPayload(manifest);
        var signature = SignLowS(canonical, LoadPrivateKey(args.Optional("private-key")));

        // Verify before writing anything: a rejected signature must not leave a manifest on
        // disk that someone can publish by mistake.
        using (var verifier = new ReleaseManifestVerifier(LoadPublicKeyBytes(args.Optional("public-key"))))
        {
            verifier.Verify(canonical, signature);
        }

        var outputDirectory = args.Require("out");
        Directory.CreateDirectory(outputDirectory);
        var manifestPath = Path.Combine(outputDirectory, "release-manifest.json");
        var signaturePath = Path.Combine(outputDirectory, "release-manifest.sig");
        File.WriteAllBytes(manifestPath, canonical);
        File.WriteAllBytes(signaturePath, signature);

        Console.WriteLine($"manifest  : {manifestPath} ({canonical.Length} bytes)");
        Console.WriteLine($"signature : {signaturePath} ({signature.Length} bytes)");
        Console.WriteLine($"sha256    : {manifest.PackageSha256}");
        Console.WriteLine("verified  : OK");
        return 0;
    }

    private static int Verify(Args args)
    {
        var manifest = File.ReadAllBytes(args.Require("manifest"));
        var signature = File.ReadAllBytes(args.Require("signature"));
        using var verifier = new ReleaseManifestVerifier(LoadPublicKeyBytes(args.Optional("public-key")));
        var verified = verifier.Verify(manifest, signature);
        Console.WriteLine($"release   : {verified.ReleaseVersion}");
        Console.WriteLine($"directory : {verified.VersionDirectory}");
        Console.WriteLine($"package   : {verified.PackageUri}");
        Console.WriteLine("verified  : OK");
        return 0;
    }

    /// <summary>
    /// Runs the finished artifacts through the real <see cref="ReleasePackageVerifier"/> —
    /// the same archive inspection, extraction and metadata comparison an installer performs.
    /// Structural mistakes in the zip surface here instead of on someone else's machine.
    /// </summary>
    private static async Task<int> VerifyPackage(Args args)
    {
        var packagePath = Path.GetFullPath(args.Require("package"));
        var manifest = File.ReadAllBytes(args.Require("manifest"));
        var signature = File.ReadAllBytes(args.Require("signature"));
        var stagingRoot = args.Optional("staging")
            ?? Path.Combine(Path.GetTempPath(), $"localai-verify-{Guid.NewGuid():N}");

        var verifier = new ReleasePackageVerifier(
            new ReleaseManifestVerifier(LoadPublicKeyBytes(args.Optional("public-key"))),
            new LocalFileReleaseClient(packagePath),
            new WindowsAuthenticodeVerifier(),
            // Only consulted when the manifest sets RequiresAuthenticode.
            new AuthenticodePublisherPolicy("CN=LocalAi", new string('0', 64)));

        var verified = await verifier.VerifyAsync(manifest, signature, stagingRoot);
        Console.WriteLine($"release  : {verified.Manifest.ReleaseVersion}");
        Console.WriteLine($"directory: {verified.Manifest.VersionDirectory}");
        Console.WriteLine("package  : OK");
        return 0;
    }

    private sealed class LocalFileReleaseClient(string path) : IReleaseClient
    {
        public Task<Stream> OpenPackageAsync(
            Uri approvedPackageUri,
            long maximumBytes,
            CancellationToken cancellationToken) =>
            Task.FromResult<Stream>(File.OpenRead(path));
    }

    /// <summary>
    /// The signed model list, and a refusal when nobody said which one.
    ///
    /// This used to default to an empty list, which is a valid manifest and a useless release:
    /// the installer installs only what the manifest names, so an omitted argument produced a
    /// release that silently installs no model at all. It stayed omitted for sixteen releases.
    /// An empty list is still publishable — but only by saying so.
    /// </summary>
    private static IReadOnlyList<ManifestModel> ReadModels(string? path, bool noModels)
    {
        if (path is null)
        {
            if (!noModels)
            {
                throw new InvalidOperationException(
                    "Missing required option --models. The installer installs only models the " +
                    "signed manifest names, so a release signed without the list installs " +
                    "none. Generate it with 'localai-release-signer models --out <file>', or " +
                    "pass --no-models to publish a release that installs none on purpose.");
            }

            return [];
        }

        if (noModels)
        {
            throw new InvalidOperationException(
                "--models and --no-models contradict each other.");
        }

        using var document = JsonDocument.Parse(File.ReadAllBytes(path));
        var models = document.RootElement.EnumerateArray()
            .Select(element => new ManifestModel(
                element.GetProperty("Name").GetString()!,
                element.GetProperty("ContextTokens").GetInt32(),
                element.GetProperty("DownloadSize").GetInt64(),
                element.GetProperty("EstimatedVramBytes").GetInt64()))
            .ToArray();
        if (models.Length == 0)
        {
            throw new InvalidOperationException(
                $"The model list at {path} is empty. Pass --no-models if that is deliberate.");
        }

        return models;
    }

    /// <summary>
    /// ECDSA produces a random s, but the verifier only accepts the canonical low-S form
    /// (s &lt;= n/2). Without this normalisation roughly half of all releases would fail.
    /// </summary>
    private static byte[] SignLowS(byte[] payload, ECDsa key)
    {
        var signature = key.SignData(
            payload,
            HashAlgorithmName.SHA256,
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation);

        var s = new BigInteger(signature.AsSpan(32, 32), isUnsigned: true, isBigEndian: true);
        if (s <= P256Order / 2)
        {
            return signature;
        }

        var flipped = (P256Order - s).ToByteArray(isUnsigned: true, isBigEndian: true);
        signature.AsSpan(32, 32).Clear();
        flipped.CopyTo(signature.AsSpan(64 - flipped.Length));
        return signature;
    }

    private static ECDsa LoadPrivateKey(string? path)
    {
        var key = ECDsa.Create();
        key.ImportPkcs8PrivateKey(File.ReadAllBytes(path ?? DefaultPrivateKeyPath()), out _);
        return key;
    }

    /// <summary>
    /// Defaults to the key embedded in the installer, so signing fails here if the private
    /// key does not match what shipped binaries trust — rather than on a user's machine.
    /// </summary>
    private static byte[] LoadPublicKeyBytes(string? path) =>
        path is null ? ReleaseTrustAnchor.PublicKey : File.ReadAllBytes(path);

    private static string DefaultPrivateKeyPath() =>
        Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "LocalAi",
            "release-signing",
            "release-signing-private.pkcs8.der");

    private static async Task<int> Release(Args args)
    {
        var version = ReleaseVersion.Parse(args.Require("version"));
        var root = args.Optional("root") ?? Directory.GetCurrentDirectory();
        var command = new ReleaseCommand(new SystemProcessRunner(), root, Console.Out);
        return args.Flag("publish")
            ? await command.PublishAsync(version)
            : await command.PrepareAsync(version);
    }

    private sealed class Args
    {
        private readonly Dictionary<string, string?> values = new(StringComparer.Ordinal);

        public static Args Parse(IEnumerable<string> tokens)
        {
            var args = new Args();
            string? pending = null;
            foreach (var token in tokens)
            {
                if (token.StartsWith("--", StringComparison.Ordinal))
                {
                    if (pending is not null)
                    {
                        args.values[pending] = null;
                    }

                    pending = token[2..];
                    args.values[pending] = null;
                    continue;
                }

                if (pending is null)
                {
                    throw new InvalidOperationException($"Unexpected argument: {token}");
                }

                args.values[pending] = token;
                pending = null;
            }

            return args;
        }

        public string Require(string name) =>
            values.TryGetValue(name, out var value) && !string.IsNullOrWhiteSpace(value)
                ? value
                : throw new InvalidOperationException($"Missing required option --{name}.");

        public string? Optional(string name) =>
            values.TryGetValue(name, out var value) && !string.IsNullOrWhiteSpace(value)
                ? value
                : null;

        public bool Flag(string name) => values.ContainsKey(name);
    }
}
