using System.Globalization;
using System.Numerics;
using System.Security.Cryptography;
using System.Text.Json;
using LocalAi.Contracts;
using LocalAi.Installer.Core.Releases;

namespace LocalAi.ReleaseSigner;

/// <summary>
/// Produces the signed release manifest that the installer verifies.
///
/// The manifest bytes are generated by <see cref="ReleaseManifestVerifier.CreateCanonicalUnsignedPayload"/>
/// rather than by a local serializer: the verifier compares the published document to that
/// canonical form byte for byte, so producing it any other way invites a silent drift that
/// only shows up as a failed installation.
/// </summary>
internal static class Program
{
    private static readonly BigInteger P256Order = BigInteger.Parse(
        "00FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551",
        NumberStyles.HexNumber);

    private static int Main(string[] args)
    {
        try
        {
            return args.FirstOrDefault() switch
            {
                "sign" => Sign(Args.Parse(args.Skip(1))),
                "verify" => Verify(Args.Parse(args.Skip(1))),
                _ => Usage(),
            };
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception.Message);
            return 1;
        }
    }

    private static int Usage()
    {
        Console.Error.WriteLine(
            """
            Usage:
              localai-release-signer sign --package <file> --package-uri <https url>
                                          --release-version <1.2.3> --version-directory <name>
                                          [--model-catalog-version <name>] [--models <file>]
                                          [--require-authenticode] [--private-key <file>]
                                          --out <directory>

              localai-release-signer verify --manifest <file> --signature <file>
                                            [--public-key <file>]

            Keys default to %LOCALAPPDATA%\LocalAi\release-signing\.
            """);
        return 2;
    }

    private static int Sign(Args args)
    {
        var packagePath = args.Require("package");
        var package = new FileInfo(packagePath);
        if (!package.Exists)
        {
            throw new InvalidOperationException($"Package not found: {packagePath}");
        }

        var manifest = new ReleaseManifest(
            schemaVersion: 1,
            releaseVersion: args.Require("release-version"),
            versionDirectory: args.Require("version-directory"),
            modelCatalogVersion: args.Optional("model-catalog-version") ?? "1",
            protocolVersion: BrokerCompatibilityContract.ProtocolVersion,
            buildCompatibilityId: BrokerCompatibilityContract.BuildCompatibilityId,
            packageUri: new Uri(args.Require("package-uri"), UriKind.Absolute),
            packageSize: package.Length,
            // The verifier accepts upper-case hex only.
            packageSha256: Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(packagePath))),
            requiresAuthenticode: args.Flag("require-authenticode"),
            models: ReadModels(args.Optional("models")));

        // Throws if any field violates the manifest contract, so a bad release fails here
        // rather than on the user's machine.
        var canonical = ReleaseManifestVerifier.CreateCanonicalUnsignedPayload(manifest);
        var signature = SignLowS(canonical, LoadPrivateKey(args.Optional("private-key")));

        var outputDirectory = args.Require("out");
        Directory.CreateDirectory(outputDirectory);
        var manifestPath = Path.Combine(outputDirectory, "release-manifest.json");
        var signaturePath = Path.Combine(outputDirectory, "release-manifest.sig");
        File.WriteAllBytes(manifestPath, canonical);
        File.WriteAllBytes(signaturePath, signature);

        // Prove the artifacts verify before anyone publishes them.
        using var verifier = new ReleaseManifestVerifier(LoadPublicKeyBytes(args.Optional("public-key")));
        verifier.Verify(canonical, signature);

        Console.WriteLine($"manifest  : {manifestPath} ({canonical.Length} bytes)");
        Console.WriteLine($"signature : {signaturePath} ({signature.Length} bytes)");
        Console.WriteLine($"sha256    : {manifest.PackageSha256}");
        Console.WriteLine("verified  : OK");
        return 0;
    }

    private static int Verify(Args args)
    {
        var manifest = File.ReadAllBytes(args.Require("manifest"));
        var signature = File.ReadAllBytes(args.Require("signature"));
        using var verifier = new ReleaseManifestVerifier(LoadPublicKeyBytes(args.Optional("public-key")));
        var verified = verifier.Verify(manifest, signature);
        Console.WriteLine($"release   : {verified.ReleaseVersion}");
        Console.WriteLine($"directory : {verified.VersionDirectory}");
        Console.WriteLine($"package   : {verified.PackageUri}");
        Console.WriteLine("verified  : OK");
        return 0;
    }

    private static IReadOnlyList<ManifestModel> ReadModels(string? path)
    {
        if (path is null)
        {
            return [];
        }

        using var document = JsonDocument.Parse(File.ReadAllBytes(path));
        return document.RootElement.EnumerateArray()
            .Select(element => new ManifestModel(
                element.GetProperty("Name").GetString()!,
                element.GetProperty("ContextTokens").GetInt32(),
                element.GetProperty("DownloadSize").GetInt64(),
                element.GetProperty("EstimatedVramBytes").GetInt64()))
            .ToArray();
    }

    /// <summary>
    /// ECDSA produces a random s, but the verifier only accepts the canonical low-S form
    /// (s &lt;= n/2). Without this normalisation roughly half of all releases would fail.
    /// </summary>
    private static byte[] SignLowS(byte[] payload, ECDsa key)
    {
        var signature = key.SignData(
            payload,
            HashAlgorithmName.SHA256,
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation);

        var s = new BigInteger(signature.AsSpan(32, 32), isUnsigned: true, isBigEndian: true);
        if (s <= P256Order / 2)
        {
            return signature;
        }

        var flipped = (P256Order - s).ToByteArray(isUnsigned: true, isBigEndian: true);
        signature.AsSpan(32, 32).Clear();
        flipped.CopyTo(signature.AsSpan(64 - flipped.Length));
        return signature;
    }

    private static ECDsa LoadPrivateKey(string? path)
    {
        var key = ECDsa.Create();
        key.ImportPkcs8PrivateKey(File.ReadAllBytes(path ?? DefaultKeyPath("private.pkcs8")), out _);
        return key;
    }

    private static byte[] LoadPublicKeyBytes(string? path) =>
        File.ReadAllBytes(path ?? DefaultKeyPath("public.spki"));

    private static string DefaultKeyPath(string kind) =>
        Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "LocalAi",
            "release-signing",
            $"release-signing-{kind}.der");

    private sealed class Args
    {
        private readonly Dictionary<string, string?> values = new(StringComparer.Ordinal);

        public static Args Parse(IEnumerable<string> tokens)
        {
            var args = new Args();
            string? pending = null;
            foreach (var token in tokens)
            {
                if (token.StartsWith("--", StringComparison.Ordinal))
                {
                    if (pending is not null)
                    {
                        args.values[pending] = null;
                    }

                    pending = token[2..];
                    args.values[pending] = null;
                    continue;
                }

                if (pending is null)
                {
                    throw new InvalidOperationException($"Unexpected argument: {token}");
                }

                args.values[pending] = token;
                pending = null;
            }

            return args;
        }

        public string Require(string name) =>
            values.TryGetValue(name, out var value) && !string.IsNullOrWhiteSpace(value)
                ? value
                : throw new InvalidOperationException($"Missing required option --{name}.");

        public string? Optional(string name) =>
            values.TryGetValue(name, out var value) && !string.IsNullOrWhiteSpace(value)
                ? value
                : null;

        public bool Flag(string name) => values.ContainsKey(name);
    }
}
