<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LocalAi.Repository\LocalAi.Repository.csproj" />
    <ProjectReference Include="..\..\src\LocalAi.Contracts\LocalAi.Contracts.csproj" />
  </ItemGroup>
</Project>
