using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CodeSearch.Core.Chunking;

/// <summary>
/// Splits C# by syntactic unit rather than by file. This is the whole point of the tool: one
/// vector per file averages a 500-line service down to a single blurred point, while one vector
/// per method keeps "what does this code do" answerable.
///
/// Granularity chosen deliberately:
/// <list type="bullet">
/// <item>One chunk per type, carrying its doc comment, its fields/properties, and a signature-only
/// table of contents of its methods. This answers "what is this entity / what does this class hold".</item>
/// <item>One chunk per executable member (method, constructor, operator, indexer, non-trivial
/// property). This answers "where is the logic that does X".</item>
/// </list>
/// Fields and auto-properties deliberately do NOT get their own chunks — a 20-property DTO would
/// otherwise produce 21 near-worthless vectors and inflate the index for nothing.
/// </summary>
public sealed class RoslynChunker : IChunker
{
    public IEnumerable<Chunk> Split(string relPath, string content)
    {
        if (LooksGenerated(content))
        {
            yield break;
        }

        var tree = CSharpSyntaxTree.ParseText(content);
        var root = (CompilationUnitSyntax)tree.GetRoot();
        var types = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>().ToList();

        if (types.Count == 0)
        {
            // Top-level statements, global usings, or a file of nothing but attributes.
            // Still worth one whole-file chunk so the file is reachable at all.
            foreach (var chunk in WholeFile(relPath, content, tree))
            {
                yield return chunk;
            }

            yield break;
        }

        foreach (var type in types)
        {
            var ns = NamespaceOf(type);
            var typePath = TypePath(type);

            yield return TypeChunk(relPath, tree, type, ns, typePath);

            if (type is not TypeDeclarationSyntax typeDecl)
            {
                continue; // enums and delegates have no executable members
            }

            foreach (var member in typeDecl.Members)
            {
                if (!IsOwnChunk(member))
                {
                    continue;
                }

                foreach (var chunk in MemberChunks(relPath, tree, member, ns, typePath))
                {
                    yield return chunk;
                }
            }
        }
    }

    /// <summary>
    /// Roslyn parses generated files perfectly well; the problem is that they bury real code in
    /// search results. The standard marker has to appear near the top to count.
    /// </summary>
    private static bool LooksGenerated(string content)
    {
        var head = content.Length > 500 ? content[..500] : content;
        return head.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }

    private static IEnumerable<Chunk> WholeFile(string relPath, string content, SyntaxTree tree)
    {
        var lines = SourceLines.Split(content);
        if (lines.Length == 0 || string.IsNullOrWhiteSpace(content))
        {
            yield break;
        }

        var header = $"File: {relPath}\n";
        foreach (var chunk in SplitByLines(
                     relPath, ChunkKind.File, Path.GetFileName(relPath), relPath,
                     NamespaceOf(tree.GetRoot()), header, lines, 1, lines.Length))
        {
            yield return chunk;
        }
    }

    private static Chunk TypeChunk(
        string relPath, SyntaxTree tree, BaseTypeDeclarationSyntax type, string ns, string typePath)
    {
        var (startLine, endLine) = LineSpan(tree, type);
        var declaration = DeclarationHeader(type);

        var body = new StringBuilder();
        body.Append("File: ").AppendLine(relPath);
        if (ns.Length > 0)
        {
            body.Append("Namespace: ").AppendLine(ns);
        }

        var doc = DocComment(type);
        if (doc.Length > 0)
        {
            body.AppendLine(doc);
        }

        body.AppendLine(declaration);

        if (type is TypeDeclarationSyntax typeDecl)
        {
            foreach (var member in typeDecl.Members)
            {
                // State first (that's what the type *is*), then a signature-only index of its
                // behaviour so the type chunk can answer "does this class have a Close method".
                body.Append("    ").AppendLine(MemberSummaryLine(member));
            }
        }
        else if (type is EnumDeclarationSyntax enumDecl)
        {
            foreach (var member in enumDecl.Members)
            {
                body.Append("    ").AppendLine(Collapse(member.ToString(), 120));
            }
        }

        var text = Truncate(body.ToString(), ChunkLimits.MaxChars);

        return new Chunk
        {
            RelPath = relPath,
            Kind = ChunkKind.Type,
            Symbol = typePath,
            Signature = declaration,
            Namespace = ns,
            StartLine = startLine,
            EndLine = endLine,
            EmbedText = text,
        };
    }

    private static IEnumerable<Chunk> MemberChunks(
        string relPath, SyntaxTree tree, MemberDeclarationSyntax member, string ns, string typePath)
    {
        var (startLine, endLine) = LineSpan(tree, member);
        var name = MemberName(member);
        var symbol = $"{typePath}.{name}";
        var signature = SignatureOf(member);

        var header = new StringBuilder();
        header.Append("File: ").AppendLine(relPath);
        if (ns.Length > 0)
        {
            header.Append("Namespace: ").AppendLine(ns);
        }

        header.Append("Type: ").AppendLine(typePath);

        var doc = DocComment(member);
        if (doc.Length > 0)
        {
            header.AppendLine(doc);
        }

        var memberLines = SourceLines.Split(member.ToString());

        return SplitByLines(
            relPath, ChunkKind.Method, symbol, signature, ns, header.ToString(),
            memberLines, startLine, endLine);
    }

    /// <summary>
    /// Emits one chunk, or several overlapping ones when the source runs past the char budget.
    /// Every part repeats the header (namespace/type/signature) so a part read on its own still
    /// says what it belongs to, and line numbers stay exact rather than estimated.
    /// </summary>
    private static IEnumerable<Chunk> SplitByLines(
        string relPath, ChunkKind kind, string symbol, string signature, string ns,
        string header, string[] lines, int firstLine, int lastLine)
    {
        var whole = header + string.Join("\n", lines);
        if (whole.Length <= ChunkLimits.MaxChars)
        {
            yield return new Chunk
            {
                RelPath = relPath,
                Kind = kind,
                Symbol = symbol,
                Signature = signature,
                Namespace = ns,
                StartLine = firstLine,
                EndLine = lastLine,
                EmbedText = whole,
            };

            yield break;
        }

        // Size the window from the file's own average line length rather than a fixed line count:
        // a 300-char-per-line generated-ish file and a terse one should both land near the budget.
        var budget = ChunkLimits.MaxChars - header.Length;
        var avgLineLength = Math.Max(1, whole.Length / Math.Max(1, lines.Length));
        var windowLines = Math.Max(20, budget / avgLineLength);
        var step = Math.Max(1, windowLines - ChunkLimits.SplitOverlapLines);
        var totalParts = (int)Math.Ceiling((double)lines.Length / step);

        var part = 0;
        for (var offset = 0; offset < lines.Length; offset += step)
        {
            var end = Math.Min(offset + windowLines, lines.Length);
            part++;

            var text = Truncate(header + string.Join("\n", lines[offset..end]), ChunkLimits.MaxChars);

            yield return new Chunk
            {
                RelPath = relPath,
                Kind = kind,
                Symbol = $"{symbol} [{part}/{totalParts}]",
                Signature = signature,
                Namespace = ns,
                StartLine = firstLine + offset,
                EndLine = Math.Min(lastLine, firstLine + end - 1),
                EmbedText = text,
            };

            if (end == lines.Length)
            {
                break;
            }
        }
    }

    /// <summary>
    /// Which members earn their own vector. Auto-properties and fields do not — they ride along
    /// in the type chunk. A property with real logic in it does.
    /// </summary>
    private static bool IsOwnChunk(MemberDeclarationSyntax member) => member switch
    {
        MethodDeclarationSyntax => true,
        ConstructorDeclarationSyntax => true,
        DestructorDeclarationSyntax => true,
        OperatorDeclarationSyntax => true,
        ConversionOperatorDeclarationSyntax => true,
        IndexerDeclarationSyntax => true,
        PropertyDeclarationSyntax p => HasRealBody(p),
        _ => false,
    };

    private static bool HasRealBody(PropertyDeclarationSyntax property)
    {
        if (property.ExpressionBody is not null)
        {
            return property.ExpressionBody.Expression.ToString().Length > 80;
        }

        return property.AccessorList?.Accessors.Any(a => a.Body is not null) == true;
    }

    private static string MemberSummaryLine(MemberDeclarationSyntax member) => member switch
    {
        FieldDeclarationSyntax or EventFieldDeclarationSyntax => Collapse(member.ToString(), 200),
        PropertyDeclarationSyntax p => Collapse(
            $"{p.Modifiers} {p.Type} {p.Identifier}{AccessorSummary(p)}", 200),
        _ => Collapse(SignatureOf(member), 200),
    };

    private static string AccessorSummary(PropertyDeclarationSyntax property)
    {
        if (property.AccessorList is null)
        {
            return string.Empty;
        }

        var kinds = property.AccessorList.Accessors.Select(a => a.Keyword.Text);
        return " { " + string.Join("; ", kinds) + "; }";
    }

    private static string SignatureOf(MemberDeclarationSyntax member) => Collapse(member switch
    {
        MethodDeclarationSyntax m =>
            $"{m.Modifiers} {m.ReturnType} {m.Identifier}{m.TypeParameterList}{m.ParameterList}",
        ConstructorDeclarationSyntax c => $"{c.Modifiers} {c.Identifier}{c.ParameterList}",
        DestructorDeclarationSyntax d => $"~{d.Identifier}()",
        OperatorDeclarationSyntax o =>
            $"{o.Modifiers} operator {o.OperatorToken}{o.ParameterList}",
        ConversionOperatorDeclarationSyntax c =>
            $"{c.Modifiers} operator {c.Type}{c.ParameterList}",
        IndexerDeclarationSyntax i => $"{i.Modifiers} {i.Type} this{i.ParameterList}",
        PropertyDeclarationSyntax p => $"{p.Modifiers} {p.Type} {p.Identifier}",
        _ => member.ToString(),
    }, 400);

    private static string MemberName(MemberDeclarationSyntax member) => member switch
    {
        MethodDeclarationSyntax m => m.Identifier.Text,
        ConstructorDeclarationSyntax c => c.Identifier.Text,
        DestructorDeclarationSyntax d => "~" + d.Identifier.Text,
        OperatorDeclarationSyntax o => "operator " + o.OperatorToken.Text,
        ConversionOperatorDeclarationSyntax c => "operator " + c.Type,
        IndexerDeclarationSyntax => "this[]",
        PropertyDeclarationSyntax p => p.Identifier.Text,
        _ => "?",
    };

    private static string DeclarationHeader(BaseTypeDeclarationSyntax type)
    {
        var text = type switch
        {
            TypeDeclarationSyntax t =>
                $"{t.Modifiers} {t.Keyword} {t.Identifier}{t.TypeParameterList}{t.ParameterList}{t.BaseList}",
            EnumDeclarationSyntax e => $"{e.Modifiers} enum {e.Identifier}{e.BaseList}",
            _ => type.Identifier.Text,
        };

        return Collapse(text, 400);
    }

    /// <summary>Dotted path through containing types, so a nested type reads as <c>Outer.Inner</c>.</summary>
    private static string TypePath(BaseTypeDeclarationSyntax type)
    {
        var parts = new List<string> { type.Identifier.Text };
        for (var parent = type.Parent; parent is not null; parent = parent.Parent)
        {
            if (parent is BaseTypeDeclarationSyntax outer)
            {
                parts.Insert(0, outer.Identifier.Text);
            }
        }

        return string.Join('.', parts);
    }

    private static string NamespaceOf(SyntaxNode node)
    {
        for (var current = node; current is not null; current = current.Parent)
        {
            if (current is BaseNamespaceDeclarationSyntax ns)
            {
                return ns.Name.ToString();
            }
        }

        // File-scoped namespaces are not ancestors of a CompilationUnit's descendants in the way
        // block-scoped ones are, so fall back to scanning the unit itself.
        var declared = node.SyntaxTree.GetRoot()
            .DescendantNodes()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault();

        return declared?.Name.ToString() ?? string.Empty;
    }

    private static string DocComment(SyntaxNode node)
    {
        var trivia = node.GetLeadingTrivia()
            .Where(t => t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) ||
                        t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
            .Select(t => t.ToFullString())
            .ToList();

        if (trivia.Count == 0)
        {
            return string.Empty;
        }

        return string.Join('\n', SourceLines.Split(string.Concat(trivia))
            .Select(l => l.Trim())
            .Where(l => l.Length > 0));
    }

    private static (int Start, int End) LineSpan(SyntaxTree tree, SyntaxNode node)
    {
        var span = tree.GetLineSpan(node.Span);
        return (span.StartLinePosition.Line + 1, span.EndLinePosition.Line + 1);
    }

    private static string Collapse(string text, int max)
    {
        var flattened = string.Join(' ', SourceLines.Split(text)
            .Select(l => l.Trim())
            .Where(l => l.Length > 0));

        return Truncate(flattened, max);
    }

    private static string Truncate(string text, int max) =>
        text.Length <= max ? text : text[..max];
}
